"""cascade delete sales and orders

Revision ID: 5d42c69ec6c1
Revises: f845b6581dd4
Create Date: 2026-05-30 13:08:58.153977
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5d42c69ec6c1'
down_revision: Union[str, None] = 'f845b6581dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_book_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('sales_book_id_fkey', 'sales', type_='foreignkey')
    op.create_foreign_key(None, 'sales', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.create_foreign_key('sales_book_id_fkey', 'sales', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_book_id_fkey', 'orders', 'books', ['book_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
