"""fix cascade

Revision ID: 8b334763f649
Revises: 5d42c69ec6c1
Create Date: 2026-05-30 13:20:45.277084
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8b334763f649'
down_revision: Union[str, None] = '5d42c69ec6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
